
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Container, Logo, Navigation } from '@/components'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mikayel Petrosyan | Front End Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen relative">
          <Container className="flex justify-between pt-7">
            <Logo />
            <Navigation />
          </Container>

          {children}
        </main>
      </body>
    </html>
  )
}
